<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div style="overflow-y:auto;max-height: 756px; text-align: center " class="col-lg-12 ">
    <h3>BİEN YAPI ÜRÜNLERİ SAN. TURZ. VE TİC A.Ş. KİŞİSEL VERİLERİN KORUNMASI POLİTİKASI</h3>
</div>
<div style="overflow-y:auto;max-height: 756px; padding-left:50px;padding-right: 50px " class="col-lg-12 ">

    <p>Kişisel verilerin korunması, BİEN YAPI ÜRÜNLERİ SAN. TURZ. VE TİC ANONİM Şirketi (“BİEN YAPI ÜRÜNLERİ SAN. TURZ. VE TİC A.Ş.” veya “Şirket”) için önem arz etmekte olup, bu hususta yürürlükte bulunan tüm mevzuata uygun davranmak için azami gayret göstermektedir. BİEN YAPI ÜRÜNLERİ SAN. TURZ. VE TİC A.Ş. , 6698 sayılı Kişisel Verilerin Korunması Kanunu (KVKK) gereğince uluslararası standartlarda bir veri koruma ve işleme politikası uygulamaktadır. 6698 Sayılı Kişisel Verilerin Korunması Kanunu’nun 10. maddesi kapsamında, BİEN YAPI ÜRÜNLERİ SAN. TURZ. VE TİC A.Ş. , kendi iş ve çalışmaları özelinde, bizzat “veri sorumlusu” sıfatıyla, “aydınlatma yükümlülüğü” nün yerine getirilmesi amacıyla Kişisel Verilerin Korunması Politikasındaki (Politika) bilgi ve ilkeler BİEN YAPI ÜRÜNLERİ SAN. TURZ. VE TİC A.Ş. için geçerlidir. Şirketimiz, Kişisel Verilerin korunması hakkındaki uygulamalarımız ve yasal düzenlemeler hakkında güncel bilgiler sunmak amacıyla Politikada değişiklikler yapma hakkını saklı tutmaktadır. Politikada yapılan değişikliklerin esaslı değişiklikler olması halinde Veri Sahipleri çeşitli kanallar aracılığıyla bilgilendirilecektir.<p>

    <p>1-GENEL BİLGİLENDİRME BİEN YAPI ÜRÜNLERİ SAN. TURZ. VE TİC A.Ş. , kişisel verilerinizi, mevzuat tarafından öngörülen sınırlar dâhilinde, aşağıdaki şekilde işlemektedir.</p>
    <p> 1.1.Kişisel Verilerin Toplanma Yöntemi: İşlenen kişisel veriler, ürün ve hizmetlerimizin türü ve niteliğine göre değişebilmektedir. Kişisel verilerinizi otomatik ya da otomatik olmayan yöntemlerle, ofislerimiz, çağrı merkezimiz, internet sitemiz, sosyal medya mecralarımız, iş ilişkisi içerisinde olduğumuz şube ve bayiler ve benzeri vasıtalarla sözlü, yazılı ya da elektronik olarak toplayabilmekteyiz. Tarafımıza ait ürün ve hizmetlerden yararlandığınız müddetçe kişisel verileriniz işlenebilecek ve verilerinizin doğruluğunu ve güncelliğini sağlamak amacıyla gerektiğinde güncellenebilecektir. Ayrıca, ürün ve hizmetlerimizden yararlanmak amacıyla, Şirket ofis binalarını, şubelerini, bayilerini, mağaza ve merkezlerini fiziken ziyaret ettiğinizde veya çağrı merkezlerini kullandığınızda, internet sayfaları ve/veya sair sosyal ve dijital mecraları ziyaret ettiğinizde veya Şirketimizin düzenlediği etkinlik, seminer, organizasyon, eğitim gibi faaliyetlere katıldığınızda da kişisel verileriniz işlenebilecektir.</p>
    <p>1.2. Kişisel Verilerin İşlenme Amaçları ve Usul: Elde edilen Kişisel Verileriniz, Şirketimiz tarafından Kanun’un 5. ve 6. maddelerinde belirtilen Kişisel Veri İşleme şartları kapsamında ve;</p>

    <p>1.2.1. Şirkete özel ticari faaliyetlerin kurgulanması, koordine edilmesi, geliştirilmesi, icrası, iş geliştirmeye yönelik faaliyetlerin planlanması ve icrası kapsamında; • Hukuken gerekli işlemlerin/kayıtların bildirimlerin gerçekleştirilmesi, yükümlülüklerin ifası, resmi kurumlarla iletişim, yetkili kurumlara bilgi verilmesi • Sözleşmelerin kurulması, ifası ve müşterilerle ilişkilerin yürütülmesi, yönetilmesi, planlanması ve icrası ile sözleşme sonrası hizmetlerin gerçekleştirilmesi, • Dışarıdan hizmet/danışmanlık vb. alımına yönelik faaliyetlerin takibi, planlanması ve icrası • Finans ve muhasebeye yönelik faaliyetlerin planlanması, takibi ve icrası • Stratejik planlama faaliyetlerinin icrası • Bilişim teknolojileri ve veri güvenliği faaliyetlerinin planlanması ve icrası • Kontrol, veri yönetimi, analiz, sosyal amaçlı aktivite, süreç geliştirme ve benzeri faaliyetlere yönelik çalışmalar ile ilgili raporlamaların gerçekleştirilmesi • Kriz ve acil durum yönetimine yönelik faaliyetlerin planlanması ve icrası • Şirketin fiziki/elektronik güvenliğine yönelik çalışmaların planlanması ve icrası</p>

    <p>1.2.2.Marka bilinilirliğini artırmak kapsamında; • Kurum, kurum faaliyetleri ve marka hakkındaki algı düzeyini artırmaya yönelik aksiyonların planlanması ve icrası • Organizasyon, toplantı, davet ve etkinliklerin planlanması, yönetimi ve icrası</p>

    <p>1.2.3.Talep ve şikayet yönetimi ile satış sonrası süreçlerin kurgulanması ve/veya icrası kapsamında; • Talep ve şikayetlerin alınması, değerlendirilmesi ve sonuçlandırılmasına yönelik talep ve şikayet yönetimi faaliyetlerin planlanması ve icrası • Sözleşme ilişkisi içerisine girmeye veya sözleşme yenilemeye yönelik operasyon, araştırma, analiz, raporlama faaliyetlerinin gerçekleştirilmesi • Sözleşmesel ilişkiden doğan yükümlülüklerin yerine getirilmesine yönelik işlem ve faaliyetlerin gerçekleştirilmesi ve takibi</p>

    <p>1.2.4.Kurumsal ilişkilerinin planlanması, icrası ve yönetilmesi; • Tedarikçi/ /iş ortağı ile ilişkilerin yönetimi, geliştirilmesi, planlanması ve icrası • Araç kiralama sözleşmelerinin kurulması ve ifasına yönelik faaliyetlerin ve gerekliliklerin yerine getirilmesi • Kurumsal yönetim ve iletişim faaliyetlerin kurgulanması ve icrası • Şirket dışı eğitim/ burs verme/ destek verme gibi faaliyetlerin planlanması ve icrası</p>

    <p>1.2.5.Şirket'in ve Şirket'le iş ilişkisi içerisinde olan ilgili kişilerin hukuki, teknik ve ticari-iş güvenliğinin temin edilmesi kapsamında; • Yetkili kurum ve kuruluşlara hukuki yükümlülük nedeniyle bilgi verilmesi ve/veya denetime ilişkin faaliyet ve yükümlülüklerin ifası • Şirket ve yerleşkelerinin ve şirketin ilişki içerisinde olduğu tarafların fiziki ve/veya elektronik ortamlarının güvenliğinin temini • Organizasyon ve etkinliklere katılan kişilerin kayıtlarının tutulması • Şirketin iş ilişkisi içerisinde olduğu taraflara ilişkin kayıtların tutulması, ticari güvenliğe yönelik çalışmaların organize edilmesi, icrası ve denetimi • Verilerin doğru ve güncel olarak tutulmasını sağlanmasına yönelik faaliyetlerin yerine getirilmesi • İş Sağlığı ve/veya güvenliği süreçlerinin planlanması ve/veya icrası • Şirkete giriş-çıkış yapan her türlü ziyaretçiye ilişkin çalışmaların hukuka uygun şekilde planlanması ve icrası gibi amaçlar dahilinde işlenebilecektir.</p>

    <p>1.3.Kişisel Verilerin İşlenmesi: a.Kişisel Veri Sahibinin Açık Rızasının Bulunması Kişisel verilerin işlenme şartlarından biri veri sahibinin açık rızasıdır. Kişisel veri sahibinin açık rızası belirli bir konuya ilişkin, bilgilendirilmeye dayalı olarak ve özgür iradeyle açıklanmalıdır. Veri, sahibinin açık rızası kapsamında ve açık rızada belirtilen amaçlarla işlenir. Kural olarak, aşağıdaki diğer şartların varlığı halinde veri sahibinin ayrıca açık rızasının alınmasına gerek bulunmamaktadır. b.Kanunlarda Açıkça Öngörülmesi Kanunda açıkça öngörülmesi halinde, veri sahibinin kişisel verileri, hukuka uygun olarak işlenir. Kanunlarda veri işlemeye izin verilen hallerde, ilgili kanunda yer alan sebep ve veri kategorileri ile sınırlı olarak veri işlenir. c.Fiili İmkânsızlık Sebebiyle İlgilinin Açık Rızasının Alınamaması Fiili imkânsızlık nedeniyle rızasını açıklayamayacak durumda olan veya rızasına geçerlilik tanınamayacak olan kişinin kendisinin ya da başka bir kişinin hayatı veya beden bütünlüğünü korumak için kişisel verisinin işlenmesinin zorunlu olması halinde veri sahibinin kişisel verileri işlenebilir. d.Sözleşmenin Kurulması veya İfasıyla Doğrudan İlgi Olması Bir sözleşmenin kurulması veya ifasıyla doğrudan doğruya ilgili olması kaydıyla, sözleşmenin taraflarına ait kişisel verilerin işlenmesinin gerekli olması halinde (sözleşmenin kurulması veya ifasına dayalı olarak verisi işlenecek kişinin sözleşmenin taraflarından birisi olması koşuluyla) kişisel veriler işlenebilir. e.Hukuki Yükümlülüğün Yerine Getirmesi Şirketimizin hukuki yükümlülüklerini yerine getirmesi için veri işlemenin zorunlu olması halinde, veri sahibinin kişisel verileri işlenebilir. f.Kişisel Veri Sahibinin Kişisel Verisini Alenileştirmesi Veri sahibinin kişisel verisinin, kendisi tarafından alenileştirilmiş olması halinde, alenileştirme amacı ile sınırlı olarak, ilgili kişisel veriler işlenebilir. g.Bir Hakkın Tesisi veya Korunması için Veri İşlemenin Zorunlu Olması Bir hakkın tesisi, kullanılması veya korunması için veri işlemenin zorunlu olması halinde veri sahibinin kişisel verileri işlenebilecektir. h.Meşru Menfaatler Nedeniyle Veri İşlemenin Zorunlu Olması Kişisel veri sahibinin temel hak ve özgürlüklerine zarar vermemek kaydıyla Şirketimizin meşru menfaatleri için veri işlemenin zorunlu olması halinde veri sahibinin kişisel verileri işlenebilir.</p>

    <p>1.4.Özel Nitelikli Kişisel Verilerin Korunması Özel nitelikli kişisel veriler Şirketimiz tarafından, işbu Politika’da belirtilen ilkelere uygun olarak ve Kurul’un belirleyeceği yöntemler de dahil olmak üzere gerekli her türlü idari ve teknik tedbirler alınarak ve aşağıdaki şartların varlığı halinde işlenmektedir: a.Sağlık ve cinsel hayat dışındaki özel nitelikli kişisel veriler, kanunlarda açıkça öngörülmesi diğer bir ifade ile ilgili faaliyetin tabi olduğu kanunda kişisel verilerin işlenmesine ilişkin açıkça bir hüküm olması halinde veri sahibinin açık rızası aranmaksızın işlenebilecektir. Aksi durumda söz konusu özel nitelikli kişisel verilerin işlenebilmesi için veri sahibinin açık rızası alınacaktır. b.Sağlık ve cinsel hayata ilişkin özel nitelikli kişisel veriler, kamu sağlığının korunması, koruyucu hekimlik, tıbbi teşhis, tedavi ve bakım hizmetlerinin yürütülmesi, sağlık hizmetleri ile finansmanının planlanması ve yönetimi amacıyla, sır saklama yükümlülüğü altında bulunan kişiler veya yetkili kurum ve kuruluşlar tarafından açık rıza aranmaksızın işlenebilecektir. Aksi durumda söz konusu özel nitelikli kişisel verilerin işlenebilmesi için veri sahibinin açık rızası alınacaktır.</p>

    <p>1.5.Kişisel Verilerin Güvenliği Şirketimiz, KVK Kanunu Madde 12’ye uygun olarak, kişisel verilerin hukuka aykırı olarak işlenmesini önlemek, bu verilere hukuka aykırı erişimleri engellemek, bunların muhafazasını sağlamak amacıyla uygun gerekli güvenlik düzeyini sağlamaya yönelik ve idari tedbirleri almakta, denetimleri yapmakta/yaptırmakta ve kişisel verilerin üçüncü kişilerce hukuka aykırı olarak işlenmesine engel olmaktadır.</p>

    <p>1.6.Kişisel Verilerin Aktarılması Kişisel veri sahibinin açık rızası olmasa dahi aşağıda belirtilen şartlardan bir ya da birkaçının mevcut olması halinde Şirketimiz tarafından gerekli özen gösterilerek ve Kurul tarafından öngörülen yöntemler de dahil gerekli tüm güvenlik önlemleri alınarak kişisel veriler, yurt içinde veya yurt dışında iş birliği içinde olduğumuz ve dışarıdan hizmet ya da destek aldığımız tedarikçilerimiz ve iş ortaklarımız; kanunen yetkili kamu kurumları ile özel kişilerle yetkileri kapsamında aktarılabilecektir. • Kişisel verilerin aktarılmasına ilişkin ilgili faaliyetlerin kanunlarda açıkça öngörülmesi, • Kişisel verilerin Şirket tarafından aktarılmasının bir sözleşmenin kurulması veya ifasıyla doğrudan doğruya ilgili ve gerekli olması, • Kişisel verilerin aktarılmasının Şirketimizin hukuki yükümlülüğünü yerine getirebilmesi için zorunlu olması, • Kişisel verilerin veri sahibi tarafından alenileştirilmiş olması şartıyla, alenileştirme amacıyla sınırlı bir şekilde Şirketimiz tarafından aktarılması, • Kişisel verilerin Şirket tarafından aktarılmasının Şirket’in veya veri sahibinin veya üçüncü kişilerin haklarının tesisi, kullanılması veya korunması için zorunlu olması, • Veri sahibinin temel hak ve özgürlüklerine zarar vermemek kaydıyla Şirket meşru menfaatleri için kişisel veri aktarımı faaliyetinde bulunulmasının zorunlu olması, • Fiili imkansızlık nedeniyle rızasını açıklayamayacak durumda bulunan veya rızasına hukuki geçerlilik tanınmayan kişinin kendisinin ya da bir başkasının hayatı veya beden bütünlüğünü koruması için zorunlu olması.

        Yukarıdakilere ek olarak kişisel veriler, Kurul tarafından yeterli korumaya sahip olduğu ilan edilen yabancı ülkelere (“Yeterli Korumaya Sahip Yabancı Ülke”) yukarıdaki şartlardan herhangi birinin varlığı halinde aktarılabilecektir. Yeterli korumanın bulunmaması durumunda ise mevzuatta öngörülen veri aktarım şartları doğrultusunda Türkiye’deki ve ilgili yabancı ülkedeki veri sorumlularının yeterli bir korumayı yazılı olarak taahhüt ettiği ve Kişisel Verileri Koruma Kurulu’nun izninin bulunduğu yabancı ülkelere (“Yeterli Korumayı Taahhüt Eden Veri Sorumlusunun Bulunduğu Yabancı Ülke”) aktarılabilecektir. Kanun’un 8. ve 9. maddesinde yer alan veri işleme şartlarına uygun hareket etmek kaydıyla kişisel verileriniz ayrıca; • Ercan Topluluk Şirketlerine, (Ercan Topluluk Şirketlerinin güncel listesi için lütfen tıklayınız) (Ercan Şirketler Topluluğu’nun katılımını gerektiren ticari faaliyetlerinin yürütülmesini temin etmek amacıyla) • Şirket iş ortaklarına (İş ortaklığının kurulma amaçlarının yerine getirilmesini temin etmek amacıyla), • Şirket tedarikçilerine, (tedarikçiden dış kaynaklı olarak temin ettiği ve şirketin ticari faaliyetlerini yerine getirmek için gerekli hizmetlerin şirketimize sunulmasını sağlamak amacıyla) • Kanunen yetkili kamu kurum ve kuruluşlarına,(İlgili kamu kurum ve kuruluşlarının hukuki yetkisi dahilinde talep ettiği amaçla sınırlı olarak ) • Kanunen yetkili özel hukuk kişilerine,(İlgili özel hukuk kişilerinin hukuki yetkisi dahilinde talep ettiği amaçla sınırlı olarak ) • İş birliği içerisinde olduğumuz bankalara, • Dışarıdan destek alınan hukuk büroları, mahkeme ve diğer resmi-adli merciler ile paylaşılmaktadır.</p>

    <p>1.7.Kişisel Veri Sahibinin Hakları Kişisel veri sahipleri KVKK m.11 uyarınca aşağıda yer alan haklara sahiptirler: a) Kişisel veri işlenip işlenmediğini öğrenme, b) Kişisel verileri işlenmişse buna ilişkin bilgi talep etme, c) Kişisel verilerin işlenme amacını ve bunların amacına uygun kullanılıp kullanılmadığını öğrenme, ç) Yurt içinde veya yurt dışında kişisel verilerin aktarıldığı üçüncü kişileri bilme, d) Kişisel verilerin eksik veya yanlış işlenmiş olması hâlinde bunların düzeltilmesini isteme, e) Kişisel verilerin eksik veya yanlış işlenmiş olması hâlinde bunların düzeltilmesini isteme ve bu kapsamda yapılan işlemin kişisel verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme, f) KVKK ve ilgili diğer kanun hükümlerine uygun olarak işlenmiş olmasına rağmen, işlenmesini gerektiren sebeplerin ortadan kalkması hâlinde kişisel verilerin silinmesini veya yok edilmesini isteme ve bu kapsamda yapılan işlemin kişisel verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme, g) İşlenen verilerin münhasıran otomatik sistemler vasıtasıyla analiz edilmesi suretiyle kişinin kendisi aleyhine bir sonucun ortaya çıkmasına itiraz etme, ğ) Kişisel verilerin kanuna aykırı olarak işlenmesi sebebiyle zarara uğraması hâlinde zararın giderilmesini talep etme. Paylaştığınız bilgilerin/verilerin doğru olması ve güncel bir şekilde muhafaza edilmesi, KVKK anlamında veri üzerinde sahip olunan hakların kullanabilmesi ve ilgili diğer mevzuat açısından önemli olup, yanlış bilgi verilmesinden doğacak sorumluluklar tamamen veri sahibine aittir. Kişisel veri sahipleri, işbu maddede sayılan haklarına ilişkin taleplerini Kurul’un belirlemiş olduğu yöntemlerle Şirketimize iletebileceklerdir. Bu doğrultuda www.bienseramik.com.tr adresinden ulaşılabilecek “Veri Sahibi Başvuru Formu”ndan yararlanabileceklerdir.</p>

    <p>2- TEMEL İLKELER Şirketimiz kişisel verilerin korunması ve işlenmesiyle ilgili olarak mevzuatta yer verilen genel ilkeler ile şartları karşılar ve kişisel verilerin Anayasa’ya ve KVKK’ ya uygun olarak işlenmesini sağlamak amacıyla aşağıda sıralanan ilkelere uygun hareket eder. </p>

    <p>2.1.Kişisel Veri İşleme Faaliyetlerinin Hukuka Ve Dürüstlük Kuralına Uygun Olması BİEN YAPI ÜRÜNLERİ SAN. TURZ. VE TİC A.Ş. , KVKK’ nın 4. maddesi uyarınca kişisel verileri hukuka ve dürüstlük kuralına uygun olarak işler, veri sahiplerine karşı “şeffaflık” ilkesini benimser ve kişisel veri sahiplerine bilgilendirmede bulunur. Bilgilendirmede, açıklık ve dürüstlük esas alınır, toplanan kişisel verilerin kullanım amacı hakkında net bilgi verilir ve veriler bu çerçevede işlenir. Kişisel verinin, herhangi bir hukuki gerekçe olmaksızın, veri sahibi üzerinde olumsuz etkiye sebebiyet verecek şekilde kullanımından kaçınılır.</p>

    <p> 2.2.Kişisel Verilerin Doğru ve Gerektiğinde Güncel Olmasının Sağlanması BİEN YAPI ÜRÜNLERİ SAN. TURZ. VE TİC A.Ş. , işlediği kişisel verilerin doğru ve güncel olmasını sağlar. </p>

    <p>2.3.Kişisel Verilerin Belirli, Açık ve Meşru Amaçlarla İşlenmesi BİEN YAPI ÜRÜNLERİ SAN. TURZ. VE TİC A.Ş. kişisel verileri meşru ve hukuka uygun sebeplerle toplar ve işler. BİEN YAPI ÜRÜNLERİ SAN. TURZ. VE TİC A.Ş. kişisel verileri, yürütmekte oldukları faaliyetlerle bağlantılı olarak, makul çerçevede ve gerekli olduğu ölçüde işler. </p>

    <p>2.4.İşlendikleri Amaçla Bağlantılı, Sınırlı ve Ölçülü Olma BİEN YAPI ÜRÜNLERİ SAN. TURZ. VE TİC A.Ş. ,işleme amacı ile ilgili olmayan veya ihtiyaç duyulmayan kişisel verileri işlemekten kaçınır. Bu çerçevede, veri işleme faaliyetinin en aza indirilmesi esastır. </p>

    <p>2.5.Kişisel Verilerin Saklanması ve İmhası Şirketimiz Türk Ceza Kanunu Madde 138 ve KVKK Madde 4 ve Madde 7’ye uygun olarak, işledikleri kişisel verileri, yalnızca ilgili mevzuat ve kanunlarda öngörülen veya kişisel veri işleme amacının gerektirdiği süre kadar muhafaza etmektedir. Bu kapsamda şirketimiz öncelikle işlemeye konu kişisel verilerin saklanması için ilgili mevzuatta belirli bir süre öngörülüp öngörülmediği tespit etmektedir. Yasal bir süre belirlenmişse, bu süreye uygun davranmaktadır. Yasal süre belirlenmemişse, işleme amacının gerçekleşmesi için gerekli olan süre belirlenir ve kişisel veriler bu süreyle sınırlı olarak saklanmaktadır. Kişisel veriler belirlenen saklama sürelerinin sonunda periyodik imha sürelerine veya veri sahibi başvurusuna uygun olarak ve belirlenen imha yöntemleri (silme ve/veya yok etme ve/veya anonimleştirme) ile imha edilmektedir.</p>

    <p>3-YÜRÜRLÜK VE UYGULAMA Bu Politika 25.06.2018 tarihinde yürürlüğe girmiştir. Politika’nın tamamının veya belirli maddelerinin güncellenmesi durumunda güncellemeler yayımlandıkları tarihte yürürlüğe girer. Politika en güncel hali iles www.bienseramik.com.tr sitesinde yayımlanır. 4-VERİ SAHİPLERİ TARAFINDAN HAKLARIN KULLANILMASI Haklarınıza ilişkin taleplerinizi www.bienseramik.com.tr ’dan ulaşabileceğiniz Veri Sahibi Başvuru Formu’nu doldurarak, tarafımıza iletmeniz durumunda, talebinizin niteliğine göre talebiniz en kısa sürede ve en geç 30 (otuz) gün içinde ücretsiz olarak sonuçlandıracaktır. Ancak, işlemin ayrıca bir maliyeti gerektirmesi hâlinde, Kişisel Verileri Koruma Kurulu’nca belirlenen tarifedeki ücret alınacaktır. Sizin adınıza üçüncü kişilerin başvuru talebinde bulunabilmesi için, bu üçüncü kişiye noterlikçe düzenlenmiş özel vekaletname vermiş olmanız gerekmektedir. Şirketimiz, başvuruda bulunan kişinin Veri Sahibi olup olmadığını tespit etmek adına İlgili Kişiden bilgi talep edebilecek, başvuruda belirtilen hususları netleştirmek adına, Veri Sahibine başvurusu ile ilgili sorular yöneltebilecektir.</p>

    <p>5-VERİ SORUMLUSUNA İLİŞKİN BİLGİLER: BİEN YAPI ÜRÜNLERİ SAN. TURZ. VE TİC A.Ş., Türkiye’de yerleşik, tüzel kişiliği olan bir sermaye şirketi olarak faaliyetlerini yürütmektedir. Veri sorumlusu olarak BİEN YAPI ÜRÜNLERİ SAN. TURZ. VE TİC A.Ş. hakkında bilgiler aşağıda belirtildiği şekildedir: Unvanı : BİEN YAPI ÜRÜNLERİ SAN. TURZ. VE TİC A.Ş. Mersis Numarası :0341026431600024 Adresi :Pelitözü Köyü Fatih Sultan Mehmet Bulv. No:13 Telefonu :02282148000 Fax :02168880465 e-posta adresi :info@bienseramik.com.tr Kayıtlı Elektronik Posta (KEP) :bienyapi@hs01.kep.tr İrtibat Kişisi :Eyüp ULUDOĞAN</p>

    <p>6-TANIMLAR: İşbu metinde yer alan aşağıdaki terimlerin anlamları, 6698 Sayılı Kanun, bu Kanuna ilişkin çıkarılan Yönetmelikler ve Tebliğlerde belirtilen tanımları ifade etmekte olup aşağıdaki şekildedir. Açık Rıza : Belirli bir konuya ilişkin, bilgilendirilmeye dayanan ve özgür iradeyle açıklanan rıza. Anonim Hale Getirme : Kişisel verinin, kişisel veri niteliğini kaybedecek ve bu durumun geri alınamayacağı şekilde değiştirilmesidir. Ör: Maskeleme, toplulaştırma, veri bozma vb. tekniklerle kişisel verinin bir gerçek kişi ile ilişkilendirilemeyecek hale getirilmesi. Kişisel Veri Sahibi : Kişisel verisi işlenen gerçek kişi. Örneğin; Müşteriler, tedarikçiler, ziyaretçiler, çalışanlar ve çalışan adayları. Kişisel Veri: Kimliği belirli veya belirlenebilir gerçek kişiye ilişkin her türlü bilgi. Dolayısıyla tüzel kişilere ilişkin bilgilerin işlenmesi Kanun kapsamında değildir. Örneğin; ad-soyad, TCKN, e-posta, adres, doğum tarihi, kredi kartı numarası, banka hesap numarası vb.

        Özel Nitelikli Kişisel Veri : Irk, etnik köken, siyasi düşünce, felsefi inanç, din, mezhep veya diğer inançlar, kılık kıyafet, dernek vakıf ya da sendika üyeliği, sağlık, cinsel hayat, ceza mahkûmiyeti ve güvenlik tedbirleriyle ilgili veriler ile biyometrik ve genetik veriler özel nitelikli verilerdir. Kişisel Verilerin İşlenmesi : Kişisel verilerin tamamen veya kısmen otomatik olan ya da herhangi bir veri kayıt sisteminin parçası olmak kaydıyla otomatik olmayan yollarla elde edilmesi, kaydedilmesi, depolanması, muhafaza edilmesi, değiştirilmesi, yeniden düzenlenmesi, açıklanması, aktarılması, devralınması, elde edilebilir hâle getirilmesi, sınıflandırılması ya da kullanılmasının engellenmesi gibi veriler üzerinde gerçekleştirilen her türlü işlem. Kişisel veri saklama ve imha: Veri sorumlularının, kişisel verilerin işlendikleri amaç için gerekli olan azami süreyi belirleme işlemi ile silme, yok etme ve anonim hale getirme işlemi. Veri Sorumlusu : Kişisel verilerin işlenme amaçlarını ve vasıtalarını belirleyen, verilerin sistematik bir şekilde tutulduğu yeri (veri kayıt sistemi) yöneten kişi veri sorumlusudur. Örneğin, her bir tüzel kişilik. Veri İşleyen : Veri sorumlusunun verdiği yetkiye dayanarak onun adına kişisel veri işleyen gerçek veya tüzel kişidir. Örneğin, (varsa) BİEN YAPI ÜRÜNLERİ SAN. TURZ. VE TİC A.Ş.’nin verilerini tutan bulut bilişim firması, talimatlar çerçevesinde arama yapan call-center. Veri kayıt sistemi : Kişisel verilerin belirli kriterlere göre yapılandırılarak işlendiği kayıt sistemi. İrtibat kişisi : Türkiye’de yerleşik olan tüzel kişiler ile Türkiye’de yerleşik olmayan tüzel kişi veri sorumlusu temsilcisinin Kanun ve bu Kanuna dayalı olarak çıkarılacak ikincil düzenlemeler kapsamındaki yükümlülükleriyle ilgili olarak, Kurum ile kurulacak iletişim için veri sorumlusu tarafından Sicile kayıt esnasında bildirilen gerçek kişi.</p>


</div>
</body>
</html>
